Riley.fixes and instructions
reboot-dev/gifinator pull request #1
Opened 2021-09-09 01:26 UTC by sp33drac3r

These changes are required for gifinator to work with go1.16.6 and the current incarnation of Google Cloud Storage (as of 9/8/2021).

Changes include:
- Updated README instructions for GCS bucket permissions.
- Update README instructions for code assumptions of GCS assets.
- Use of standard library 'sort.Slice'.

2021-09-09 18:15 UTC, sp33drac3r commented
More changes required to get this to build in k8s. Removing review request for now.

2021-09-13 18:22 UTC, rjhuijsman requested changes

2021-09-13 18:22 UTC, rjhuijsman commented on k8s/gifcreator-deployment.yaml
> +>>>>>>> 6525895 (Prettier all files)
Oops! We should resolve these conflicts (here and below).

2021-09-13 18:22 UTC, rjhuijsman commented on README.md
> +Remove public access preventions and allow fine-grained access controls on the bucket you create.
Could you also drop a link to the documentation we used to create the Kubernetes service account and link it to a Google service account?

https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#authenticating_to

2021-09-13 19:48 UTC, sp33drac3r commented on k8s/gifcreator-deployment.yaml
> +>>>>>>> 6525895 (Prettier all files)
Oops! How did that happen? Good catch!

2021-09-13 19:48 UTC, sp33drac3r commented on README.md
> +Remove public access preventions and allow fine-grained access controls on the bucket you create.
Good idea. Will do

2021-09-13 22:10 UTC, rjhuijsman approved these changes

2021-09-13 22:25 UTC, merged